language: node_js
node_js: "12"

cache:
  directories:
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

sudo: required

jobs:
  include:
    -
      os: osx
      osx_image: xcode10.3
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
      name: Mac
      install:
        - brew install mpv ninja
        - npm install
      script:
        - npm run lint
        - npm run pack
        # - npm run test

    - 
      os: linux
      dist: bionic
      addons:
        apt:
          update: true
          packages:
            - g++-5
            - gcc-5
            - ninja-build
            - libboost-system-dev
            - libmpv1
            - libavformat-dev
      env: CC=gcc-5 CXX=g++-5
      name: Linux
      services:
        - xvfb
      before_script:
        - "export DISPLAY=:99.0"
      install:
        - npm install
      script:
        - npm run lint
        - npm run pack
        - npm run test
        - "[[ $TRAVIS_BRANCH == master ]] && npm run publish:linux || echo \"Skipped Deploy Step\""

notifications:
  email: false