language: node_js

node_js:
  - "10"
  - "9"

install:
  - npm install

script:
  - npm run test:server
  - npm run cloc
after_success: npm run coverage

cache:
  directories:
    - "node_modules"

notifications:
  email: false
