language: node_js
node_js: "12"

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

install:
  - npm install

jobs:
  include:
    -
      os: osx
      osx_image: xcode10.2
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
        - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7"
      name: Mac
      script:
        - npm run lint
      deploy:
        script:
          - npm run publish:mac
        on:
          branch: master
          condition: $TRAVIS_BRANCH = master

    - 
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - gcc-5
      env: CC=gcc-5 CXX=g++-5
      name: Linux
      script:
        - npm run lint
      deploy:
        script:
          - npm run publish:linux
        on:
          branch: master
          condition: $TRAVIS_BRANCH = master

notifications:
  email: false