matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: "12"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
        - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7"

    - os: linux
      language: node_js
      node_js: "12"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - gcc-5
      env: CC=gcc-5 CXX=g++-5

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

install:
  - npm install

jobs:
  include:
    -
      name: Lint
      script:
        - npm run lint
    - 
      name: Deploy
      if: branch = master
      script:
        - |
          if [ "$TRAVIS_OS_NAME" == "linux" ]; then
            npm run publish:linux
          else
            npm run publish:mac
          fi