language: node_js

node_js:
  - "10"

install:
  - npm ci

script:
  - npm run build
  - npm run test
  - npm run cloc
after_success: npm run coverage

cache:
  directories:
    - "~/.npm"
    - "~/.cache"

notifications:
  email: false
