language: node_js

node_js:
  - "8"
  - "7"

sudo: true
before_install:
  - sudo apt-get install libsecret-1-dev

install:
  - npm install

script:
  - npm run test:server
  - npm run cloc
after_success: npm run coverage

cache:
  directories:
    - "node_modules"

notifications:
  email: false
