image: Visual Studio 2017

os: unstable

cache:
  - node_modules -> package.json

skip_tags: true

environment:
  nodejs_version: "12"

platform:
  - x64

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run lint
  - npm run pack
  - npm run test

build_script:
  - IF [%APPVEYOR_REPO_BRANCH%]==[master] npm run publish:win