image: Visual Studio 2017

cache:
  - '%USERPROFILE%\.electron'

skip_tags: true

platform:
  - x64

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 12 x64
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run lint
  - npm run pack
  - npm run test

deploy_script:
  - IF [%APPVEYOR_REPO_BRANCH%]==[master] npm run publish:win