image: Visual Studio 2019

cache:
  - '%USERPROFILE%\.electron'

skip_tags: true

platform:
  - x64

init:
  - git config --global core.autocrlf input

environment:
  matrix:
    - cmake: 1
    # - variant: test_debug
    #   compiler: msvc-14.0
    #   model: 32
    #   bjam: 1
    # - variant: test_release
    #   compiler: msvc-14.0
    #   model: 64
    #   python: 1
    #   crypto: openssl
    #   bjam: 1
    - variant: test_debug
      compiler: gcc
      model: 64
      crypto: openssl
      bjam: 1

install:
  - ps: Install-Product node 12 x64
  - git submodule update --init --recursive
  - choco install ninja
  - g++ --version
  - cd %APPVEYOR_BUILD_FOLDER%\bindings\lib\libtorrent
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=14 -G Ninja ..
  - ninja
  - ninja install
  - cd %APPVEYOR_BUILD_FOLDER%
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run lint
  - npm run pack
  - npm run test

deploy_script:
  - IF [%APPVEYOR_REPO_BRANCH%]==[master] npm run publish:win