image: Visual Studio 2017

cache:
  - '%USERPROFILE%\.electron'

skip_tags: true

platform:
  - x64

init:
  - git config --global core.autocrlf input

environment:
  matrix:
    - variant: test_release
      compiler: gcc
      model: 64
      python: 1
      crypto: openssl
      bjam: 1
      cmake: 1

install:
  - ps: Install-Product node 12 x64
  - git submodule update --init --recursive

  - set ROOT_DIRECTORY=%CD%
  - cd %ROOT_DIRECTORY%
  - if not defined compiler ( set compiler="" )
  - if not defined crypto ( set crypto=built-in )
  - if not defined linkflags ( set linkflags="" )
  - if not defined include ( set include="" )
  - cd %ROOT_DIRECTORY%
  - set BOOST_ROOT=c:\Libraries\boost_1_69_0
  - set BOOST_BUILD_PATH=%BOOST_ROOT%\tools\build
  - echo %BOOST_ROOT%
  - echo %BOOST_BUILD_PATH%
  - set PATH=%PATH%;%BOOST_BUILD_PATH%\src\engine\bin.ntx86
  - ps: '"using msvc : 14.0 ;`nusing gcc : : : <cxxflags>-std=c++14 ;`n" | Set-Content $env:HOMEDRIVE\$env:HOMEPATH\user-config.jam'
  - type %HOMEDRIVE%%HOMEPATH%\user-config.jam
  - cd %ROOT_DIRECTORY%
  - set PATH=c:\msys64\mingw32\bin;%PATH%
  - g++ --version
  - echo %ROOT_DIRECTORY%
  - cd %BOOST_BUILD_PATH%\src\engine
  - build.bat >nul
  - cd %BOOST_ROOT%
  - bjam cxxstd=14 release --with-system --layout=system address-model=64 link=shared stage

  - choco install ninja

  - cd %APPVEYOR_BUILD_FOLDER%\bindings\lib\libtorrent
  - mkdir build && cd build
  - set BOOST_LIBRARYDIR=%BOOST_ROOT%\stage\lib
  - cmake -DBOOST_LIBRARYDIR=%BOOST_LIBRARYDIR% -DCMAKE_CXX_STANDARD=14 -Dbuild_tools=ON -G "Visual Studio 15 2017" -A x64 ..
  - cmake --build . --config Release -- -verbosity:minimal
  - cmake --install .
  - set "PATH=c:/Program Files (x86)/libtorrent/;%PATH%"

  - cd %APPVEYOR_BUILD_FOLDER%
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run lint
  - npm run pack
  - npm run test

deploy_script:
  - IF [%APPVEYOR_REPO_BRANCH%]==[master] npm run publish:win