image: Visual Studio 2019

cache:
  - '%USERPROFILE%\.electron'

skip_tags: true

platform:
  - x64

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 12 x64
  - choco install ninja
  - cd bindings\lib\libtorrent
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=14 -G Ninja ..
  - ninja
  - ninja install
  - cd ..\..\..\..\
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run lint
  - npm run pack
  - npm run test

deploy_script:
  - IF [%APPVEYOR_REPO_BRANCH%]==[master] npm run publish:win