image: Visual Studio 2015

cache:
  - '%USERPROFILE%\.electron'

skip_tags: true

platform:
  - x64

init:
  - git config --global core.autocrlf input

environment:
  matrix:
    - variant: test_release
      compiler: msvc-14.0
      model: 64
      python: 1
      crypto: openssl
      bjam: 1
      cmake: 1

install:
  - ps: Install-Product node 12 x64
  - git submodule update --init --recursive

  - set ROOT_DIRECTORY=%CD%
  - cd %ROOT_DIRECTORY%
  - if not defined compiler ( set compiler="" )
  - if not defined crypto ( set crypto=built-in )
  - if not defined linkflags ( set linkflags="" )
  - if not defined include ( set include="" )
  - cd %ROOT_DIRECTORY%
  - set BOOST_ROOT=c:\Libraries\boost_1_69_0
  - set BOOST_BUILD_PATH=%BOOST_ROOT%\tools\build
  - echo %BOOST_ROOT%
  - echo %BOOST_BUILD_PATH%
  - set PATH=%PATH%;%BOOST_BUILD_PATH%\src\engine\bin.ntx86
  - ps: '"using msvc : 14.0 ;`nusing gcc : : : <cxxflags>-std=c++14 ;`nusing python : 3.5 : c:\\Python35-x64 : c:\\Python35-x64\\include : c:\\Python35-x64\\libs ;`n" | Set-Content $env:HOMEDRIVE\$env:HOMEPATH\user-config.jam'
  - type %HOMEDRIVE%%HOMEPATH%\user-config.jam
  - cd %ROOT_DIRECTORY%
  - set PATH=c:\msys64\mingw32\bin;%PATH%
  - g++ --version
  - python --version
  - echo %ROOT_DIRECTORY%
  - cd %BOOST_BUILD_PATH%\src\engine
  - build.bat >nul

  - choco install ninja
  - cd %APPVEYOR_BUILD_FOLDER%\bindings\lib\libtorrent
  - mkdir build && cd build
  - set "PATH=c:\Python27-x64;%PATH%"
  - cmake -DCMAKE_CXX_STANDARD=14 -Dbuild_tools=ON -G "Visual Studio 14 2015 Win64" ..
  - ninja
  - sudo ninja install
  - cd %APPVEYOR_BUILD_FOLDER%
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run lint
  - npm run pack
  - npm run test

deploy_script:
  - IF [%APPVEYOR_REPO_BRANCH%]==[master] npm run publish:win