image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 10 x64
  - npm install

test_script:
  - npm run lint

build_script:
  - IF [%APPVEYOR_REPO_BRANCH%]==[master] npm run publish:win