image: Visual Studio 2017

os: unstable

cache:
  - node_modules -> package.json

skip_tags: true

platform:
  - x64

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 12 x64
  - npm install

test_script:
  - npm run lint
  - npm run pack
  - npm run test

build_script:
  - IF [%APPVEYOR_REPO_BRANCH%]==[master] npm run publish:win